name: build sink service docker

on:
  push:
    branches:
      - master
    paths:
      - 'docker/sink_service/Dockerfile'
      - 'sink_service/**'
      - '.github/workflows/docker_sink_service.yml'

  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to push on docker hub'
        required: true

  release:
    type: [created]

env:
  IMAGE_NAME: 'wirepas/gateway_sink_service'
  DOCKER_BUILDKIT: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: get c-mesh-api with submodule
        run: git submodule update --init

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.4.1

      - name: set tag for pushed changes
        if: github.event_name == 'push'
        run: echo '::set-env name=TAG1::${{ env.IMAGE_NAME }}:edge'

      - name: set tag for manually triggered
        if: github.event_name == 'workflow_dispatch'
        run: echo '::set-env name=TAG1::${{ env.IMAGE_NAME }}:${{ github.event.inputs.tag }}'

      - name: set tag for releases
        if: github.event_name == 'release'
        run: |
          echo '::set-env name=TAG1::${{ env.IMAGE_NAME }}:${{ github.event.release.tag_name }}'
          echo '::set-env name=TAG2::${{ env.IMAGE_NAME }}:latest'

      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/sink_service/Dockerfile
          platforms: linux/amd64,linux/arm
          push: true
          build-args: GATEWAY_BUILD_SHA1= ${{ github.sha }}
          tags: |
            ${{ env.TAG1 }}
            ${{ env.TAG2 }}

      - name: Build and extract binaries
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/sink_service/Dockerfile
          platforms: linux/amd64,linux/arm
          push: false
          target: export
          outputs: ./artifacts

      - name: Store artefacts locally
        uses: actions/upload-artifact@v2
        with:
           name: sink_service_binary
           path: ./artifacts/

      - name: Get release url
        if:  github.event_name == 'release'
        id: get_release
        uses: bruceadams/get-release@v1.2.1
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload Arm binary
        if:  github.event_name == 'release'
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./artifacts/linux_arm_v7/sinkService
          asset_name: sinkServiceArm
          asset_content_type: application/octet-stream

      - name: Upload amd64 binary
        if:  github.event_name == 'release'
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./artifacts/linux_amd64/sinkService
          asset_name: sinkServiceArm
          asset_content_type: application/octet-stream
