name: build base builder

on:
  push:
    branches: master
    paths:
      - '.github/workflows/docker_base_builder.yml'
      - 'docker/base_builder/Dockerfile'

  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to push on docker hub'
        required: true
env:
  IMAGE_NAME: 'wirepas/gateway_base_builder'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Set tag for push
        if: github.event_name == 'push'
        run: echo "TAG1=$IMAGE_NAME:edge" >> $GITHUB_ENV

      - name: Set tag for manually triggered
        if: github.event_name == 'workflow_dispatch'
        run: echo "TAG1=$IMAGE_NAME:${{ github.event.inputs.tag }}" >> $GITHUB_ENV

      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/base_builder/Dockerfile
          platforms: linux/amd64,linux/arm
          push: true
          build-args: GATEWAY_BUILD_SHA1= ${{ github.sha }}
          tags: $TAG1
